# Default values for dev-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  name: dev-portal-backend
  image:
    repository: joonahalonencgi/eurodeo-dev-portal-backend
    pullPolicy: Always
    tag: latest
  replicaCount: 1
  containerport: 8082
  debugport: 5005
  service:
    type: ClusterIP
    port: 80
    debugport: 5005
  vault_url: "http://vault.vault.svc.cluster.local:8200"
  vault_token: ""
  vault_path: apisix-dev/consumers/ewc
  vault_phase: "geeks" # This one might need to be empty string as well
  apisix_admin_url: "http://apisix-admin.apisix.svc.cluster.local:9180"
  apisix_gateway_url: "https://apisixdev.eumetnet-femdi.eumetsat.ewcloud.host"
  apisix_apikey: ""
  apisix_keypath: $secret://vault/dev/
  keycloak_cluster_url: http://keycloack-keycloak.keycloack.svc.cluster.local

frontend:
  name: dev-portal-frontend
  image:
    repository: joonahalonencgi/eurodeo-dev-portal-frontend
    pullPolicy: Always
    tag: latest
  replicaCount: 1
  containerport: 443
  service:
    type: ClusterIP
    port: 80

keycloak_url: "https://keycloak-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host"
keycloak_logout_url: "https://devportal-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host"
keycloak_realm: test

ingress:
  enabled: true
  className: nginx
  annotations: 
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: devportal-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host
    external-dns.alpha.kubernetes.io/target: 64.225.132.246
  host: devportal-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host
  tls: 
    - secretName: devportal-tls
      hosts:
        - devportal-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host

